import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { EmailTemplateEditor } from './emailTemplateEditor';
describe('EmailTemplateEditor', () => {
  beforeEach(() => vi.unstubAllGlobals());
  it('updates subject, body and theme in the fixed preview and creates a template', async () => { const close = vi.fn(); const request = vi.fn().mockResolvedValue(Response.json({ id: 't1' }, { status: 201 })); vi.stubGlobal('fetch', request); render(<EmailTemplateEditor projectId="p1" onClose={close} />); fireEvent.change(screen.getByLabelText('Тема письма'), { target: { value: 'Новая тема' } }); fireEvent.change(screen.getByLabelText('Текст письма'), { target: { value: 'Проверьте почту.' } }); fireEvent.change(screen.getByLabelText('Тема оформления'), { target: { value: 'dark' } }); expect((screen.getByLabelText('Тема письма') as HTMLInputElement).value).toBe('Новая тема'); expect(screen.getByText('Новая тема')).toBeDefined(); expect(screen.getAllByText('Проверьте почту.')).toHaveLength(2); expect(document.querySelector('[data-email-theme="dark"]')).not.toBeNull(); fireEvent.submit(screen.getByRole('button', { name: 'Сохранить письмо' }).closest('form')!); await waitFor(() => expect(close).toHaveBeenCalled()); expect(request.mock.calls[0][0]).toContain('/api/projects/p1/emailTemplates'); });
  it('loads and updates an existing template', async () => { const close = vi.fn(); const request = vi.fn().mockResolvedValueOnce(Response.json({ id: 't1', projectId: 'p1', subject: 'Saved', body: 'Body', theme: 'dark', redirectUrl: 'https://example.ru/done' })).mockResolvedValueOnce(Response.json({ id: 't1' })); vi.stubGlobal('fetch', request); render(<EmailTemplateEditor projectId="p1" templateId="t1" onClose={close} />); await screen.findByDisplayValue('Saved'); fireEvent.submit(screen.getByRole('button', { name: 'Сохранить письмо' }).closest('form')!); await waitFor(() => expect(close).toHaveBeenCalled()); expect(request.mock.calls[1][1].method).toBe('PATCH'); });
  it('shows validation, load and save errors', async () => { const close = vi.fn(); const { unmount } = render(<EmailTemplateEditor projectId="" onClose={close} />); fireEvent.change(screen.getByLabelText('URL после подтверждения'), { target: { value: 'javascript:alert(1)' } }); fireEvent.submit(screen.getByRole('button', { name: 'Сохранить письмо' }).closest('form')!); expect(screen.getByRole('alert')).toBeDefined(); unmount(); vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('offline'))); const loaded = render(<EmailTemplateEditor projectId="p1" templateId="t1" onClose={close} />); expect(await screen.findByRole('alert')).toBeDefined(); loaded.unmount(); render(<EmailTemplateEditor projectId="p1" onClose={close} />); fireEvent.submit(screen.getByRole('button', { name: 'Сохранить письмо' }).closest('form')!); expect(await screen.findByRole('alert')).toBeDefined(); });
  it('returns to the list without saving', () => { const close = vi.fn(); render(<EmailTemplateEditor projectId="p1" onClose={close} />); fireEvent.click(screen.getByRole('button', { name: '← К письмам' })); expect(close).toHaveBeenCalled(); });
});
