'use client';
import { FormEvent, useEffect, useState } from 'react';
import type { EmailTemplate } from '@/entities/emailTemplate';
export function EmailTemplateEditor({ projectId, templateId, onClose }: { projectId: string; templateId?: string; onClose: () => void }) {
  const [subject, setSubject] = useState('Подтвердите вашу заявку'); const [body, setBody] = useState('Спасибо за заявку. Подтвердите e-mail, чтобы мы могли связаться с вами.'); const [theme, setTheme] = useState<'light' | 'dark'>('light'); const [redirectUrl, setRedirectUrl] = useState('https://relayform.ru'); const [state, setState] = useState<'loading' | 'ready' | 'saving' | 'error'>(templateId ? 'loading' : 'ready');
  useEffect(() => { if (!templateId) return; queueMicrotask(() => void fetch(`/api/emailTemplates/${encodeURIComponent(templateId)}`).then(async (response) => { if (!response.ok) throw new Error(); const template = await response.json() as EmailTemplate; setSubject(template.subject); setBody(template.body); setTheme(template.theme); setRedirectUrl(template.redirectUrl); setState('ready'); }).catch(() => setState('error'))); }, [templateId]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!projectId || !isHttpUrl(redirectUrl)) return setState('error'); setState('saving'); try { const response = await fetch(templateId ? `/api/emailTemplates/${encodeURIComponent(templateId)}` : `/api/projects/${encodeURIComponent(projectId)}/emailTemplates`, { method: templateId ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ subject, body, theme, redirectUrl }) }); if (!response.ok) throw new Error(); onClose(); } catch { setState('error'); } }
  if (state === 'loading') return <p role="status">Загружаем письмо…</p>;
  return <section className="grid gap-5 lg:grid-cols-2"><article className="emailPreview order-1 self-start rounded-2xl border border-[var(--color-border-default)] p-6 lg:order-2" data-email-theme={theme}><strong>relayform</strong><h2 className="mt-8 text-2xl font-semibold">{subject}</h2><p className="mt-4 whitespace-pre-wrap opacity-75">{body}</p><button className="mt-6 rounded-lg bg-[var(--color-action-primary)] px-4 py-3 text-[var(--color-email-light-text)]" type="button">Подтвердить</button><p className="mt-8 text-xs opacity-70">Создано с помощью <a className="underline" href="https://relayform.ru">relayform.ru</a></p></article><form className="order-2 max-h-[48vh] overflow-y-auto pr-1 lg:order-1 lg:max-h-none lg:overflow-visible" onSubmit={save}><button className="text-sm underline" type="button" onClick={onClose}>← К письмам</button><h1 className="mt-5 text-3xl font-semibold">{templateId ? 'Редактировать письмо' : 'Новое письмо'}</h1>{state === 'error' && <p className="mt-4 text-sm text-[var(--color-status-danger)]" role="alert">Не удалось сохранить письмо. Проверьте поля.</p>}<label className="mt-6 block text-sm">Тема письма<input required className="mt-2 w-full rounded-lg border border-[var(--color-border-default)] bg-transparent p-3" value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label className="mt-4 block text-sm">Текст письма<textarea required className="mt-2 min-h-48 w-full rounded-lg border border-[var(--color-border-default)] bg-transparent p-3" value={body} onChange={(event) => setBody(event.target.value)} /></label><label className="mt-4 block text-sm">Тема оформления<select className="mt-2 w-full rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-surface)] p-3" value={theme} onChange={(event) => setTheme(event.target.value as 'light' | 'dark')}><option value="light">Светлая</option><option value="dark">Тёмная</option></select></label><label className="mt-4 block text-sm">URL после подтверждения<input required className="mt-2 w-full rounded-lg border border-[var(--color-border-default)] bg-transparent p-3" type="url" value={redirectUrl} onChange={(event) => setRedirectUrl(event.target.value)} /></label><button disabled={state === 'saving'} className="mt-4 rounded-lg bg-[var(--color-action-primary)] px-4 py-3 text-sm font-medium disabled:opacity-60" type="submit">{state === 'saving' ? 'Сохраняем…' : 'Сохранить письмо'}</button></form></section>;
}
function isHttpUrl(value: string) { try { return ['http:', 'https:'].includes(new URL(value).protocol); } catch { return false; } }
