'use client';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import type { EmailTemplate } from '@/entities/emailTemplate';
import type { Project } from '@/entities/project';
import { EmailTemplateEditor } from '@/features/manageEmailTemplate/ui/emailTemplateEditor';
export function EmailTemplatesPage() {
  const router = useRouter(); const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(''); const [templates, setTemplates] = useState<EmailTemplate[]>([]); const [editingId, setEditingId] = useState<string | 'new' | null>(null); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
  const loadProjects = useCallback(async () => { setState('loading'); try { const response = await fetch('/api/projects'); if (response.status === 401) return router.replace('/login'); if (!response.ok) throw new Error(); const payload = await response.json() as { projects: Project[] }; setProjects(payload.projects); setProjectId((current) => current || payload.projects[0]?.id || ''); setState('ready'); } catch { setState('error'); } }, [router]);
  const loadTemplates = useCallback(async (id: string) => { if (!id) { setTemplates([]); return; } setState('loading'); try { const response = await fetch(`/api/projects/${encodeURIComponent(id)}/emailTemplates`); if (response.status === 401) return router.replace('/login'); if (!response.ok) throw new Error(); setTemplates((await response.json() as { templates: EmailTemplate[] }).templates); setState('ready'); } catch { setState('error'); } }, [router]);
  useEffect(() => { queueMicrotask(() => void loadProjects()); }, [loadProjects]); useEffect(() => { queueMicrotask(() => void loadTemplates(projectId)); }, [loadTemplates, projectId]);
  async function closeEditor() { setEditingId(null); await loadTemplates(projectId); }
  async function remove(templateId: string) { if (!window.confirm('Удалить письмо подтверждения?')) return; try { const response = await fetch(`/api/emailTemplates/${encodeURIComponent(templateId)}`, { method: 'DELETE' }); if (!response.ok) throw new Error(); setTemplates((current) => current.filter((item) => item.id !== templateId)); } catch { setState('error'); } }
  if (editingId) return <EmailTemplateEditor projectId={projectId} templateId={editingId === 'new' ? undefined : editingId} onClose={() => void closeEditor()} />;
  return <section><button className="text-sm underline" onClick={() => router.push('/cabinet')} type="button">← В кабинет</button><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold">Письма подтверждения</h1>{projects.length > 0 && <label className="mt-4 block text-sm">Проект<select className="mt-2 block rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-surface)] p-2" value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>}</div>{projectId && <button className="rounded-lg bg-[var(--color-action-primary)] px-4 py-3 text-sm font-medium" onClick={() => setEditingId('new')} type="button">Создать письмо</button>}</div>{state === 'loading' ? <p className="mt-6" role="status">Загружаем письма…</p> : state === 'error' ? <div className="mt-6" role="alert">Не удалось загрузить данные. <button className="underline" onClick={() => void loadProjects()}>Повторить</button></div> : projects.length === 0 ? <p className="mt-6">Сначала создайте проект.</p> : templates.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-[var(--color-border-default)] p-8 text-center">Писем пока нет.</div> : <div className="mt-6 grid gap-3">{templates.map((template) => <article className="flex items-center justify-between rounded-xl border border-[var(--color-border-default)] bg-[var(--color-bg-surface)] p-5" key={template.id}><div><h2 className="font-medium">{template.subject}</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{template.theme === 'dark' ? 'Тёмная тема' : 'Светлая тема'}</p></div><div className="flex gap-3"><button className="text-sm underline" onClick={() => setEditingId(template.id)}>Редактировать</button><button className="text-sm text-[var(--color-status-danger)]" onClick={() => remove(template.id)}>Удалить</button></div></article>)}</div>}</section>;
}
