import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { EmailTemplatesPage } from './emailTemplatesPage';
const replace = vi.fn(); const push = vi.fn(); const router = { replace, push };
vi.mock('next/navigation', () => ({ useRouter: () => router }));
vi.mock('@/features/manageEmailTemplate/ui/emailTemplateEditor', () => ({ EmailTemplateEditor: ({ onClose }: { onClose: () => void }) => <div>Редактор<button onClick={onClose}>Закрыть</button></div> }));
describe('EmailTemplatesPage', () => {
  beforeEach(() => { replace.mockClear(); push.mockClear(); vi.unstubAllGlobals(); });
  it('loads, edits and deletes persisted templates', async () => { const template = { id: 't1', projectId: 'p1', subject: 'Confirm', body: 'Body', theme: 'dark', redirectUrl: 'https://example.ru' }; const request = vi.fn().mockImplementation(async (url: string, init: RequestInit = {}) => init.method === 'DELETE' ? new Response(null, { status: 204 }) : url === '/api/projects' ? Response.json({ projects: [{ id: 'p1', name: 'Site' }] }) : Response.json({ templates: [template] })); vi.stubGlobal('fetch', request); const confirm = vi.spyOn(window, 'confirm').mockReturnValueOnce(false).mockReturnValueOnce(true); render(<EmailTemplatesPage />); await screen.findByText('Confirm'); fireEvent.click(screen.getByRole('button', { name: 'Редактировать' })); expect(screen.getByText('Редактор')).toBeDefined(); fireEvent.click(screen.getByRole('button', { name: 'Закрыть' })); await screen.findByText('Confirm'); fireEvent.click(screen.getByRole('button', { name: 'Удалить' })); fireEvent.click(screen.getByRole('button', { name: 'Удалить' })); await waitFor(() => expect(screen.queryByText('Confirm')).toBeNull()); confirm.mockRestore(); });
  it('shows project and template empty states and opens create', async () => { const request = vi.fn().mockResolvedValueOnce(Response.json({ projects: [] })); vi.stubGlobal('fetch', request); const first = render(<EmailTemplatesPage />); expect(await screen.findByText('Сначала создайте проект.')).toBeDefined(); first.unmount(); vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ projects: [{ id: 'p1', name: 'Site' }] })).mockResolvedValueOnce(Response.json({ templates: [] }))); render(<EmailTemplatesPage />); await screen.findByText('Писем пока нет.'); fireEvent.click(screen.getByRole('button', { name: 'Создать письмо' })); expect(screen.getByText('Редактор')).toBeDefined(); });
  it('handles unauthorized and retryable failures', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('{}', { status: 401 }))); const first = render(<EmailTemplatesPage />); await waitFor(() => expect(replace).toHaveBeenCalledWith('/login')); first.unmount(); const request = vi.fn().mockRejectedValueOnce(new Error()).mockResolvedValueOnce(Response.json({ projects: [] })); vi.stubGlobal('fetch', request); render(<EmailTemplatesPage />); await screen.findByRole('alert'); fireEvent.click(screen.getByRole('button', { name: 'Повторить' })); expect(await screen.findByText('Сначала создайте проект.')).toBeDefined(); });
  it('keeps a template when deletion fails and returns to cabinet', async () => { const template = { id: 't1', projectId: 'p1', subject: 'Confirm', body: 'Body', theme: 'light', redirectUrl: 'https://example.ru' }; vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(Response.json({ projects: [{ id: 'p1', name: 'Site' }] })).mockResolvedValueOnce(Response.json({ templates: [template] })).mockResolvedValueOnce(new Response('{}', { status: 503 }))); const confirm = vi.spyOn(window, 'confirm').mockReturnValue(true); render(<EmailTemplatesPage />); await screen.findByText('Confirm'); fireEvent.click(screen.getByRole('button', { name: 'Удалить' })); expect(await screen.findByRole('alert')).toBeDefined(); fireEvent.click(screen.getByRole('button', { name: '← В кабинет' })); expect(push).toHaveBeenCalledWith('/cabinet'); confirm.mockRestore(); });
});
